defaults:
  - override hydra/launcher: joblib

data:
  name: "general_mnist"
  kwargs:
    batch_size: 64
    num_images_per_class: null
    x_transform: sign
    linear_projection: 100
    label_mode: "ooe"

model:
  name: "rp-sign-perceptron-ce"
  kwargs:
    input_dim: 100
    hidden_dim: 3000
    output_dim: 10
    lr: 1e-3
    loss_type: "cross_entropy"
    optim: "sgd"
    use_bias: false
    sparsity: 0.9

wandb:
  enabled: true
  entity: willinki-bocconi-university
  project: mnist-experiments
  run_name: base-${now:%Y%m%d-%H%M%S}-${model.name}
  mode: online
  dir: ${oc.env:WANDB_DIR,${hydra:runtime.output_dir}}
  tags: ["clipped-mlp", "hetero"]

# Global training knobs
epochs: 20
epochs_readout: 20

name: ${model.name}/${data.name}
master_seed: 44
