data:
  name: "general_mnist"
  kwargs:
    batch_size: 64
    num_images_per_class: null
    x_transform: sign
    linear_projection: 100
    label_mode: "c-rescale"

# Phase 1: prototype-regression MLP (clipped)
model:
  name: "clipped-3layer-mlp"
  kwargs:
    input_dim: 100
    hidden_dim: 1000
    output_dim: 10
    gain: 1.0 # kept for consistency with other builders
    lr: 1e-3
    loss_type: "argmax_margin"
    argmax_margin: 1.0
    optim: "sgd"
    use_bias: false
    clamp: true

wandb:
  enabled: true
  entity: mattia-scardecchia
  project: darnax-new-benchmarks-v2
  run_name: ${now:%Y%m%d-%H%M%S}-${model.name}
  mode: online
  dir: ${oc.env:WANDB_DIR,${hydra:runtime.output_dir}}
  tags: ["clipped-mlp", "hetero"]

# Global training knobs
epochs: 25
epochs_readout: 25

name: ${model.name}/${data.name}
master_seed: 44
