defaults:
  - override hydra/launcher: submitit_slurm

data:
  name: "general_mnist"
  num_labels: 10
  kwargs:
    batch_size: 64
    num_images_per_class: null
    x_transform: sign
    linear_projection: 100
    label_mode: "ooe"

model:
  name: "clipped-3layer-mlp"
  prototypes_distro: "gaussian"
  reset_readout: true
  kwargs:
    input_dim: 100
    hidden_dim: 1000
    output_dim: 10
    gain: 1.0 # kept for consistency with other builders
    lr: 1e-3
    loss_type: "cross_entropy"
    argmax_margin: 1.0
    optim: "sgd"
    use_bias: false
    clamp: true
    num_hidden_layers: 2

wandb:
  enabled: true
  entity: willinki-bocconi-university
  project: darnax-new-benchmarks-v3
  run_name: base-${now:%Y%m%d-%H%M%S}-${model.name}
  mode: online
  dir: ${oc.env:WANDB_DIR,${hydra:runtime.output_dir}}
  tags: ["clipped-mlp", "hetero"]

# Global training knobs
epochs: 20

name: ${model.name}/${data.name}
master_seed: 44

torch_clf:
  enabled: true
  optimizer: sgd
  epochs: 20
  lr: 0.005
  batch_size: 16
  weight_decay: 0.0
  log_prefix: torch_clf
  use_bias: false
