epochs: 100

optimizer:
  learning_rate_j: 0.005
  learning_rate_wout: ${optimizer.learning_rate_j}
  learning_rate_win: ${optimizer.learning_rate_j}
  weight_decay_j: 0.005
  weight_decay_win: ${optimizer.weight_decay_j}
  weight_decay_wout: ${optimizer.weight_decay_j}

data:
  name: general_mnist
  kwargs:
    batch_size: 16
    num_images_per_class: null
    x_transform: sign
    linear_projection: 100
    label_mode: c-rescale

trainer:
  name: dynamical
  kwargs:
    warmup_n_iter: 1
    train_clamped_n_iter: 4
    train_free_n_iter: 5
    eval_n_iter: 5

model:
  name: fc-baseline
  kwargs:
    seed: 99
    dim_data: 100
    dim_hidden: 100
    num_labels: 10
    strength_forth: 5.0
    strength_back: 1.4
    threshold_j: 1.4
    threshold_in: ${model.kwargs.threshold_j}
    threshold_out: 3.0
    j_d: 0.5

wandb:
  enabled: true
  entity: mattia-scardecchia
  project: darnax-new-benchmarks-v2
  run_name: "prova"
  mode: online
  tags:
    - fc-baseline
    - emnist
    - dynamical
  dir: /scratch/ms16518/logs/milano/wandb
  save_code: true
  reinit: false

master_seed: 44
