defaults:
  - override hydra/launcher: joblib

hydra:
  launcher:
    n_jobs: 15
    verbose: 0
    backend: multiprocessing

epochs: 20

optimizer:
  learning_rate_wout: 0.025
  learning_rate_j: 0.02
  learning_rate_win: 0.3
  learning_rate_wback: 0.0
  weight_decay_win: 0.0
  weight_decay_wout: 0.02
  weight_decay_j: 0.01
  weight_decay_wback: 0.0

data:
  name: fashion_mnist
  kwargs:
    batch_size: 16
    num_images_per_class: null
    x_transform: identity
    linear_projection: null
    label_mode: pm1

trainer:
  name: dynamical
  gating:
    enabled: false
    warmup_epochs: 0
    shift: 1.0
  fake_dynamics:
    enabled: false
    k: 0.5
    vanilla: true
  double_dynamics: true
  kwargs:
    warmup_n_iter: 1
    train_clamped_n_iter: ${trainer.kwargs.eval_n_iter}
    train_free_n_iter: ${trainer.kwargs.eval_n_iter}
    eval_n_iter: 5
    momentum: 0.0

model:
  name: fc-baseline-sparse-fully
  kwargs:
    seed: 99
    dim_data: 784
    dim_hidden: 100
    num_labels: 10
    strength_forth: 5.0
    strength_back: 2.75
    threshold_j: 1.4
    threshold_in: 1.6
    threshold_out: 7.0
    threshold_back: 0.0
    j_d: 0.9
    sparsity: 0.99
    sparsity_win: 0.9
    use_crossentropy: false
    learnable_wback: false

wandb:
  enabled: true
  entity: willinki-bocconi-university
  project: fashion_mnist-scaling
  run_name: "fc-baseline"
  mode: online
  tags:
    - prova
  dir: scratch/ms16518/logs/milano/wandb
  save_code: true
  reinit: false

master_seed: 44

torch_clf:
  enabled: true
  optimizer: sgd
  epochs: 20
  lr: 0.0015
  batch_size: 16
  weight_decay: 0.0
  log_prefix: torch_clf
  use_bias: false
