# defaults:
#   - override hydra/launcher: submitit_slurm

epochs: 20

optimizer:
  learning_rate_wout: 0.05
  learning_rate_j: 0.005
  learning_rate_win: 0.085
  weight_decay_win: 0.0
  weight_decay_wout: 0.0
  weight_decay_j: 0.01

data:
  name: general_mnist
  kwargs:
    batch_size: 16
    num_images_per_class: null
    x_transform: sign
    linear_projection: 100
    label_mode: c-rescale

trainer:
  name: dynamical
  gating:
    enabled: false
    warmup_epochs: 0
    shift: 1.0
  fake_dynamics:
    enabled: true
    k: 0.5 # fraction of spins to set to prototype values
    vanilla: true
  double_dynamics: true
  kwargs:
    warmup_n_iter: 1
    train_clamped_n_iter: ${trainer.kwargs.eval_n_iter}
    train_free_n_iter: ${trainer.kwargs.eval_n_iter}
    eval_n_iter: 5
    momentum: 0.0

model:
  name: fc-baseline
  kwargs:
    seed: 99
    dim_data: 100
    dim_hidden: 100
    num_labels: 10
    strength_forth: 5.0
    strength_back: 1.4
    threshold_j: 1.4
    threshold_in: 1.4
    threshold_out: 3.0
    j_d: 0.7

wandb:
  enabled: true
  entity: mattia-scardecchia
  project: darnax-new-benchmarks-v2
  run_name: "prova"
  mode: online
  tags:
    - prova
  dir: /scratch/ms16518/logs/milano/wandb
  save_code: true
  reinit: false

master_seed: 44

torch_clf:
  enabled: true
  epochs: 20
  lr: 0.001
  batch_size: 128
  weight_decay: 0.0
  log_prefix: torch_clf
  use_bias: false
